project:
  type: website
  output-dir: ../docs

website:
  title: "TONe - ICO"
#  sidebar:
#    contents:
  navbar:
    logo: logo-TONe-ICO.png
#    logo-href: https://npolar.no
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Troll-Observing-Network/integrated-cloud-observatory
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: dashboard.qmd
        text: Dashboards
      - href: team.qmd
        text: Team

format:
  html:
    theme: 
      - darkly
    css: styles.css
    toc: true

bibliography: references.bib
